/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package class_jframes;

import class_control.Controle_Regex;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import lesclasses.Client;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Stagiaire
 */
public class Formulaire_Client extends javax.swing.JFrame {

    //**************************************************************************//
    //         Declaration des attributs de la class Formulaire_Client
    //**************************************************************************//
    
    //  Declaration d un Client pour instanciation avec les differents champs du
    //  formulaire pour creation ou modification
    private Client leClient = null;
    //  Declaration d un Controle regex pour controler la validite des champs du
    //  formulaire
    private Controle_Regex regClient;
    //  boolean qui passe a true si on est sur un formulaire de modification
    private boolean bModif = false;
    //  Declaration des variables qui stockeront les champs du formulaire apres
    //  controle des champs
    private int     numId;
    private String  raison = null;
    private String  type = null;
    private String  domaine = null;
    private String  adresse = null;
    private String  tel = null;
    private int     chiffre;
    private String  commentaire = null;
    private int     nbrEmp;
    private Date    date = null;
    private String  mail = null;
    
    //**************************************************************************//
    //         Declaration des constructeurs de la class Formulaire_Client
    //**************************************************************************//
    
    /**
     * Creates new form Formulaire_Client
     * Constructeur par defaut
     */
    public Formulaire_Client() {
        initComponents();
        this.setLocationRelativeTo(null);
        //  Initialisation du format du jXDatepicker
        this.jXDtp_DateContrat.setDate(Calendar.getInstance().getTime());
        this.jXDtp_DateContrat.setFormats(new SimpleDateFormat("dd-MM-yyy"));
        //  Initialisation du titre de la fenetre
        this.jLbl_Formulaire_Titre.setText("Création d'un Client");
    }

    /**
    * Creates new form Formulaire_Client
    * Constructeur appele lors de la modification d un Client
    * @param modifClient
    */
    public Formulaire_Client(Client modifClient) {
        initComponents();
        this.setLocationRelativeTo(null);
        //  On recupere le Client selectionne a l ecran d accueil
        this.leClient = modifClient;
        //  Initialisation du format du jXDatepicker
        this.jXDtp_DateContrat.setDate(Calendar.getInstance().getTime());
        this.jXDtp_DateContrat.setFormats(new SimpleDateFormat("dd-MM-yyy"));
        //  On charge les differents champs du formulaire
        champ_A_Modifier();
        //  On passe le boolean de modification a true
        this.bModif = true;
        this.jLbl_Formulaire_Titre.setText("Modification d'un Client");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_Formulaire_Titre = new javax.swing.JLabel();
        jBtn_Retour = new javax.swing.JButton();
        jBtn_Valider = new javax.swing.JButton();
        jLbl_numIdentification = new javax.swing.JLabel();
        jLbl_RaisonSociale = new javax.swing.JLabel();
        jLbl_TypeSociete = new javax.swing.JLabel();
        jLbl_Domaine = new javax.swing.JLabel();
        jLbl_Adresse = new javax.swing.JLabel();
        jLbl_Telephone = new javax.swing.JLabel();
        jLbl_ChiffreAffaire = new javax.swing.JLabel();
        jLbl_NbEmploye = new javax.swing.JLabel();
        jLbl_Commentaires = new javax.swing.JLabel();
        jLbl_DateContrat = new javax.swing.JLabel();
        jLbl_adrMail = new javax.swing.JLabel();
        jTbx_NumIdentification = new javax.swing.JTextField();
        jTbx_RaisonSociale = new javax.swing.JTextField();
        jCbx_TypeSociete = new javax.swing.JComboBox<>();
        jTbx_Domaine = new javax.swing.JTextField();
        jTbx_Adresse = new javax.swing.JTextField();
        jTbx_NumTel = new javax.swing.JTextField();
        jTbx_ChiffreAffaire = new javax.swing.JTextField();
        jTbx_NbEmploye = new javax.swing.JTextField();
        jTbx_AdrMail = new javax.swing.JTextField();
        jSPane_Commentaires = new javax.swing.JScrollPane();
        jTxa_Commentaires = new javax.swing.JTextArea();
        jXDtp_DateContrat = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fenêtre de Formulaire");

        jLbl_Formulaire_Titre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLbl_Formulaire_Titre.setText("Text formulaire Client");

        jBtn_Retour.setText("<< RETOUR");
        jBtn_Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RetourActionPerformed(evt);
            }
        });

        jBtn_Valider.setText("VALIDER");
        jBtn_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ValiderActionPerformed(evt);
            }
        });

        jLbl_numIdentification.setText("Numéro d'indentification :");

        jLbl_RaisonSociale.setText("Raison Sociale :");

        jLbl_TypeSociete.setText("Type de la société :");

        jLbl_Domaine.setText("Domaine de la société :");

        jLbl_Adresse.setText("Adresse :");

        jLbl_Telephone.setText("Numéro de téléphone :");

        jLbl_ChiffreAffaire.setText("Chiffre d'affaire :");

        jLbl_NbEmploye.setText("Nombre d'employé(s) :");

        jLbl_Commentaires.setText("Commentaires :");

        jLbl_DateContrat.setText("Date du contrat : ");

        jLbl_adrMail.setText("Adresse mail :");

        jTbx_NumIdentification.setEditable(false);
        jTbx_NumIdentification.setEnabled(false);
        jTbx_NumIdentification.setFocusable(false);

        jCbx_TypeSociete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "privé", "public" }));

        jTxa_Commentaires.setColumns(20);
        jTxa_Commentaires.setRows(5);
        jSPane_Commentaires.setViewportView(jTxa_Commentaires);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLbl_Formulaire_Titre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbx_TypeSociete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_RaisonSociale, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_Domaine, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_NumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_ChiffreAffaire, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_AdrMail, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDtp_DateContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_Valider)
                            .addComponent(jLbl_numIdentification)
                            .addComponent(jLbl_RaisonSociale)
                            .addComponent(jLbl_TypeSociete)
                            .addComponent(jLbl_Domaine)
                            .addComponent(jLbl_Adresse)
                            .addComponent(jLbl_Telephone)
                            .addComponent(jLbl_ChiffreAffaire)
                            .addComponent(jLbl_DateContrat))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtn_Retour))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(203, 203, 203)
                                        .addComponent(jLbl_NbEmploye)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTbx_NbEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTbx_NumIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_adrMail)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbl_Commentaires)
                                .addGap(18, 18, 18)
                                .addComponent(jSPane_Commentaires, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_Formulaire_Titre)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_numIdentification)
                    .addComponent(jTbx_NumIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_RaisonSociale)
                    .addComponent(jTbx_RaisonSociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_TypeSociete)
                    .addComponent(jCbx_TypeSociete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Domaine)
                    .addComponent(jTbx_Domaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Adresse)
                    .addComponent(jTbx_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Telephone)
                    .addComponent(jTbx_NumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_ChiffreAffaire)
                    .addComponent(jTbx_ChiffreAffaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_NbEmploye)
                    .addComponent(jTbx_NbEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_DateContrat)
                    .addComponent(jXDtp_DateContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_adrMail)
                    .addComponent(jTbx_AdrMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSPane_Commentaires, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jBtn_Retour)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbl_Commentaires)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_Valider)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //---------------------Controle du DatePicker-------------------------------
    
     /**
     * Methode qui controle la validite de la date de contrat
     * @return 
     */
    private boolean controlDateContrat(){
        boolean bDateCont = false;
        Date dateNow = Calendar.getInstance().getTime();
        Date inputDate = jXDtp_DateContrat.getDate();
        if(inputDate.after(dateNow)){
            showMessageDialog(null, "La date de contrat ne peut pas être supérieur à la date du jour");
        }
        else{
            bDateCont = true;
        }
        return bDateCont;
    }    
    
    //------------Controle de la coherence CA / nombre employe(s)---------------
    
    /**
     * Methode qui verifie que le chiffre d affaire n est pas 1 000 000 superieur
     * au nombre d employ(s)
     * @return 
     */
    private boolean erreurCa_Emp(){
        boolean bStatus = false;
        int ca = Integer.parseInt(jTbx_ChiffreAffaire.getText());
        int emp = Integer.parseInt(jTbx_NbEmploye.getText());
        if(ca > 1000000*emp){
            showMessageDialog(null, "Problème de cohérence entre le chiffre d'affaire "
                    + "et le nombre d'employé(s)");
        }else{
            bStatus = true;
        }
        return bStatus;
    }
    //**************************************************************************//
    //              DEBUT controle des saisies utilisateur                      //
    //**************************************************************************//
    
    /**
     * Methode pour charger les champs du formulaire avec les valeurs du Client
     * a modifier
     */
    private void champ_A_Modifier(){
        jTbx_NumIdentification.setText(String.valueOf(leClient.getIdent()));
        jTbx_RaisonSociale.setText(leClient.getRaison());
        jCbx_TypeSociete.setSelectedItem(leClient.getTypeSo());
        jTbx_Domaine.setText(leClient.getDomaine());
        jTbx_Adresse.setText(leClient.getAdresse());
        jTbx_NumTel.setText(leClient.getTel());
        jTbx_ChiffreAffaire.setText(String.valueOf(leClient.getCa()));
        jTbx_NbEmploye.setText(String.valueOf(leClient.getNbrEmp()));
        jXDtp_DateContrat.setDate(leClient.getDateContrat());
        jTbx_AdrMail.setText(leClient.getAdresseMail());
        jTxa_Commentaires.setText(leClient.getComment());
    }
    
    /**
     * Methode qui controle que tous les champs du formulaire sont valides
     * et recupere la valeur de ses champs
     * @return 
     */
    private boolean validFormulaire(){
        //  On initialise la variable a false
        boolean bValid = false;
        //  On instancie objet Controle_Regex
        regClient = new Controle_Regex();
        try {
            //  On verifie que toutes les saisies sont valides 
            if(regClient.controlRaison(jTbx_RaisonSociale.getText())
                && regClient.controlDomaine(jTbx_Domaine.getText())
                && regClient.controlAdresse(jTbx_Adresse.getText())
                && regClient.controlNumTel( jTbx_NumTel.getText())
                && regClient.controlChiffrAffaire(jTbx_ChiffreAffaire.getText())
                && regClient.controlNbEmploye(jTbx_NbEmploye.getText())
                && controlDateContrat()
                && regClient.controlMail(jTbx_AdrMail.getText())
                && regClient.controlCommentaire(jTxa_Commentaires.getText())
                && erreurCa_Emp()){ 
                
                //  Si tout est bon
                bValid = true;
                //  On recupere la valeur des champs saisies                
                raison = jTbx_RaisonSociale.getText(); 
                type = jCbx_TypeSociete.getSelectedItem().toString();
                domaine = jTbx_Domaine.getText();            
                adresse = jTbx_Adresse.getText();            
                tel =  jTbx_NumTel.getText();            
                chiffre = Integer.parseInt(jTbx_ChiffreAffaire.getText());                          
                nbrEmp = Integer.parseInt(jTbx_NbEmploye.getText());            
                commentaire = jTxa_Commentaires.getText();            
                date = jXDtp_DateContrat.getDate();            
                mail = jTbx_AdrMail.getText();                              
            }            
        }catch(Exception ex){
            showMessageDialog(null, ex.getMessage());
            bValid = false;
        }        
        return bValid;
    }
    
    //**************************************************************************//
    //              FIN controle des saisies utilisateur                        //
    //**************************************************************************//
        
    /**
     * Methode associee au bouton de retour
     * @param evt 
     */
    private void jBtn_RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RetourActionPerformed
        JFrame_Accueil ecranAccueil = null;
        try {
            ecranAccueil = new JFrame_Accueil(0);
        } catch (Exception ex) {
            Logger.getLogger(Formulaire_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        ecranAccueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtn_RetourActionPerformed
     
    /**
     * Methode associee au bouton valider qui apres verification de la saisie
     * utilisateur creer ou met a jour un Client
     * @param evt 
     */
    private void jBtn_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ValiderActionPerformed
        if(validFormulaire()){
            //  Si formulaire de modification
            if(bModif){                
                numId = Integer.parseInt(jTbx_NumIdentification.getText());
                try {
                    leClient = new Client(numId, raison, type, domaine, adresse, tel, chiffre, commentaire, nbrEmp, date, mail);
                    leClient.MiseAJour();
                } catch (Exception ex) {
                    Logger.getLogger(Formulaire_Client.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //  Sinon c est une creation
            else {
                try {
                leClient = new Client(raison, type, domaine, adresse, tel, chiffre, commentaire, nbrEmp, date, mail);
                leClient.Creation();
                } catch (Exception ex) {
                    Logger.getLogger(Formulaire_Client.class.getName()).log(Level.SEVERE, null, ex);
                }  
            }            
            //  On instancie une nouvelle fenetre d 'accueil qui sera mise a jour
            JFrame_Accueil ecranAccueil = null;
            try {
                ecranAccueil = new JFrame_Accueil(0);
            } catch (Exception ex) {
                Logger.getLogger(Formulaire_Client.class.getName()).log(Level.SEVERE, null, ex);
            }
            ecranAccueil.setVisible(true);
            this.dispose();    
        }
        
        else{
            showMessageDialog(null, "Erreur lors de la validation du formulaire !");
        }
    }//GEN-LAST:event_jBtn_ValiderActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Retour;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JComboBox<String> jCbx_TypeSociete;
    private javax.swing.JLabel jLbl_Adresse;
    private javax.swing.JLabel jLbl_ChiffreAffaire;
    private javax.swing.JLabel jLbl_Commentaires;
    private javax.swing.JLabel jLbl_DateContrat;
    private javax.swing.JLabel jLbl_Domaine;
    private javax.swing.JLabel jLbl_Formulaire_Titre;
    private javax.swing.JLabel jLbl_NbEmploye;
    private javax.swing.JLabel jLbl_RaisonSociale;
    private javax.swing.JLabel jLbl_Telephone;
    private javax.swing.JLabel jLbl_TypeSociete;
    private javax.swing.JLabel jLbl_adrMail;
    private javax.swing.JLabel jLbl_numIdentification;
    private javax.swing.JScrollPane jSPane_Commentaires;
    private javax.swing.JTextField jTbx_AdrMail;
    private javax.swing.JTextField jTbx_Adresse;
    private javax.swing.JTextField jTbx_ChiffreAffaire;
    private javax.swing.JTextField jTbx_Domaine;
    private javax.swing.JTextField jTbx_NbEmploye;
    private javax.swing.JTextField jTbx_NumIdentification;
    private javax.swing.JTextField jTbx_NumTel;
    private javax.swing.JTextField jTbx_RaisonSociale;
    private javax.swing.JTextArea jTxa_Commentaires;
    private org.jdesktop.swingx.JXDatePicker jXDtp_DateContrat;
    // End of variables declaration//GEN-END:variables
}
