/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package class_jframes;

import class_control.Controle_Regex;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import lesclasses.Prospect;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Stagiaire
 */
public class Formulaire_Prospect extends javax.swing.JFrame {
       
    //**************************************************************************//
    //         Declaration des attributs de la class Formulaire_Client
    //**************************************************************************//
    
    //  Declaration d un Prospect pour instanciation avec les differents champs du
    //  formulaire pour creation ou modification
    private Prospect leProspect = null;
    //  Declaration d un Controle regex pour controler la validite des champs du
    //  formulaire
    private Controle_Regex regProspect;
    //  boolean qui passe a true si on est sur un formulaire de modification
    private boolean bModif = false;
    //  Declaration des variables qui stockeront les champs du formulaire apres
    //  controle des champs
    private int         numId;
    private String      raison = null;
    private String      type = null;
    private String      domaine = null;
    private String      adresse = null;
    private String      tel = null;
    private int         chiffre;
    private String      commentaire = null;
    private int         nbrEmp;
    private Date        date = null;
    private Boolean     interest;
    
    //**************************************************************************//
    //         Declaration des constructeurs de la class Formulaire_Client
    //**************************************************************************//
    
    /**
     * Creates new form Formulaire_Client
     */
    public Formulaire_Prospect() {
        initComponents();
        //  On centre la fenetre
        this.setLocationRelativeTo(null);
        //  Initialisation du format du jXDatepicker
        this.jXDtp_DateProspection.setDate(Calendar.getInstance().getTime());
        this.jXDtp_DateProspection.setFormats(new SimpleDateFormat("dd-MM-yyy"));              
        //  Initialisation du titre de la fenetre
        this.jLbl_Formulaire_Titre.setText("Création d'un Prospect");
    }

     /**
     * Creates new form Formulaire_Client
     * Constructeur appele lors de la modification d un Client
     * @param modifProspect
     */
    public Formulaire_Prospect(Prospect modifProspect) {
        initComponents();
        this.setLocationRelativeTo(null);
        //  On recupere le Client selectionne a l ecran d accueil
        this.leProspect = modifProspect;
        //  Initialisation du format du jXDatepicker
        this.jXDtp_DateProspection.setDate(Calendar.getInstance().getTime());
        this.jXDtp_DateProspection.setFormats(new SimpleDateFormat("dd-MM-yyy"));
        //  On charge les differents champs du formulaire
        champ_A_Modifier();
        //  On passe le boolean de modification a true
        this.bModif = true;
        this.jLbl_Formulaire_Titre.setText("Modification d'un Prospect");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_Formulaire_Titre = new javax.swing.JLabel();
        jBtn_Retour = new javax.swing.JButton();
        jBtn_Valider = new javax.swing.JButton();
        jLbl_numIdentification = new javax.swing.JLabel();
        jLbl_RaisonSociale = new javax.swing.JLabel();
        jLbl_TypeSociete = new javax.swing.JLabel();
        jLbl_Domaine = new javax.swing.JLabel();
        jLbl_Adresse = new javax.swing.JLabel();
        jLbl_Telephone = new javax.swing.JLabel();
        jLbl_ChiffreAffaire = new javax.swing.JLabel();
        jLbl_NbEmploye = new javax.swing.JLabel();
        jLbl_Commentaires = new javax.swing.JLabel();
        jLbl_DateContrat = new javax.swing.JLabel();
        jLbl_adrMail = new javax.swing.JLabel();
        jTbx_NumIdentification = new javax.swing.JTextField();
        jTbx_RaisonSociale = new javax.swing.JTextField();
        jCbx_TypeSociete = new javax.swing.JComboBox<>();
        jTbx_Domaine = new javax.swing.JTextField();
        jTbx_Adresse = new javax.swing.JTextField();
        jTbx_NumTel = new javax.swing.JTextField();
        jTbx_ChiffreAffaire = new javax.swing.JTextField();
        jTbx_NbEmploye = new javax.swing.JTextField();
        jSPane_Commentaires = new javax.swing.JScrollPane();
        jTxa_Commentaires = new javax.swing.JTextArea();
        jXDtp_DateProspection = new org.jdesktop.swingx.JXDatePicker();
        jCkbx_InteretTrue = new javax.swing.JCheckBox();
        jCkbx_InteretFalse = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fenêtre de Formulaire");

        jLbl_Formulaire_Titre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLbl_Formulaire_Titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Formulaire_Titre.setText("Text formulaire Prospect");

        jBtn_Retour.setText("<< RETOUR");
        jBtn_Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RetourActionPerformed(evt);
            }
        });

        jBtn_Valider.setText("VALIDER");
        jBtn_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ValiderActionPerformed(evt);
            }
        });

        jLbl_numIdentification.setText("Numéro d'indentification :");

        jLbl_RaisonSociale.setText("Raison Sociale :");

        jLbl_TypeSociete.setText("Type de la société :");

        jLbl_Domaine.setText("Domaine de la société :");

        jLbl_Adresse.setText("Adresse :");

        jLbl_Telephone.setText("Numéro de téléphone :");

        jLbl_ChiffreAffaire.setText("Chiffre d'affaire :");

        jLbl_NbEmploye.setText("Nombre d'employé(s) :");

        jLbl_Commentaires.setText("Commentaires :");

        jLbl_DateContrat.setText("Date du prospection  : ");

        jLbl_adrMail.setText("Intérêt du Prospect :");

        jTbx_NumIdentification.setEditable(false);

        jCbx_TypeSociete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "privé", "public" }));

        jTxa_Commentaires.setColumns(20);
        jTxa_Commentaires.setRows(5);
        jSPane_Commentaires.setViewportView(jTxa_Commentaires);

        jCkbx_InteretTrue.setText("Oui");
        jCkbx_InteretTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCkbx_InteretTrueActionPerformed(evt);
            }
        });

        jCkbx_InteretFalse.setText("Non");
        jCkbx_InteretFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCkbx_InteretFalseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLbl_Formulaire_Titre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbx_TypeSociete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_RaisonSociale, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_Domaine, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_NumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbx_ChiffreAffaire, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDtp_DateProspection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCkbx_InteretTrue)
                                .addGap(72, 72, 72)
                                .addComponent(jCkbx_InteretFalse)))))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_Valider)
                            .addComponent(jLbl_numIdentification)
                            .addComponent(jLbl_RaisonSociale)
                            .addComponent(jLbl_TypeSociete)
                            .addComponent(jLbl_Domaine)
                            .addComponent(jLbl_Adresse)
                            .addComponent(jLbl_Telephone)
                            .addComponent(jLbl_ChiffreAffaire)
                            .addComponent(jLbl_DateContrat))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtn_Retour))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(203, 203, 203)
                                        .addComponent(jLbl_NbEmploye)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTbx_NbEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTbx_NumIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_adrMail)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbl_Commentaires)
                                .addGap(18, 18, 18)
                                .addComponent(jSPane_Commentaires, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_Formulaire_Titre)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_numIdentification)
                    .addComponent(jTbx_NumIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_RaisonSociale)
                    .addComponent(jTbx_RaisonSociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_TypeSociete)
                    .addComponent(jCbx_TypeSociete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Domaine)
                    .addComponent(jTbx_Domaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Adresse)
                    .addComponent(jTbx_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Telephone)
                    .addComponent(jTbx_NumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_ChiffreAffaire)
                    .addComponent(jTbx_ChiffreAffaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_NbEmploye)
                    .addComponent(jTbx_NbEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_DateContrat)
                    .addComponent(jXDtp_DateProspection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_adrMail)
                    .addComponent(jCkbx_InteretTrue)
                    .addComponent(jCkbx_InteretFalse))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSPane_Commentaires, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jBtn_Retour)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbl_Commentaires)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_Valider)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //---------------------Controle du DatePicker-------------------------------
    
     /**
     * Methode qui controle la validite de la date de contrat
     * @return 
     */
    private boolean controlDateContrat(){
        boolean bDateCont = false;
        Date dateNow = Calendar.getInstance().getTime();
        Date inputDate = jXDtp_DateProspection.getDate();
        if(inputDate.after(dateNow)){
            showMessageDialog(null, "La date de contrat ne peut pas être supérieur à la date du jour");
        }
        else{
            bDateCont = true;
        }
        return bDateCont;
    }  
 
    //--------------------------Les CheckBox------------------------------------
    
    /**
     * Methode qui controle qu'une des deux CheckBox a été coché
     * @return 
     */
    private boolean controlInteret(){
        boolean bInteret;
        if((jCkbx_InteretTrue.isSelected()) || (jCkbx_InteretFalse.isSelected())){
            bInteret = true;
        }
        else{
            bInteret = false;
            showMessageDialog(null, "Veuillez cocher l'intérêt du Prospect");
        }
        return bInteret;
    }         
    
    /**
     * Methode qui retourne si le Prospect et interesse ou pas
     * @return 
     */
    private boolean choixInteret(){
        boolean bChoix = (jCkbx_InteretTrue.isSelected()) ? true : false;
        return bChoix;
    }
    
    //**************************************************************************//
    //              DEBUT controle des saisies utilisateur                      //
    //**************************************************************************//
    
    /**
     * Methode pour charger les champs du formulaire avec les valeurs du Client
     * a modifier
     */
    private void champ_A_Modifier(){
        jTbx_NumIdentification.setText(String.valueOf(leProspect.getIdent()));
        jTbx_RaisonSociale.setText(leProspect.getRaison());
        jCbx_TypeSociete.setSelectedItem(leProspect.getTypeSo());
        jTbx_Domaine.setText(leProspect.getDomaine());
        jTbx_Adresse.setText(leProspect.getAdresse());
        jTbx_NumTel.setText(leProspect.getTel());
        jTbx_ChiffreAffaire.setText(String.valueOf(leProspect.getCa()));
        jTbx_NbEmploye.setText(String.valueOf(leProspect.getNbrEmp()));
        jXDtp_DateProspection.setDate(leProspect.getDateProspetc());
        if(leProspect.getInteretPropspect()){
            jCkbx_InteretTrue.setSelected(true);
        }else{
            jCkbx_InteretFalse.setSelected(true);
        }
        jTxa_Commentaires.setText(leProspect.getComment());
    }    
    
    /**
     * Methode qui controle que tous les champs du formulaire sont valides
     * et recupere la valeur de ses champs
     * @return 
     */
    private boolean validFormulaire(){
        //  On initialise la variable a false
        boolean bValid = false;
        //  On instancie un objet Controle_Regex
        regProspect = new Controle_Regex();
        try {
            //  On verifie que toutes les saisies sont valides 
            if(regProspect.controlRaison(jTbx_RaisonSociale.getText())
                && regProspect.controlDomaine(jTbx_Domaine.getText())
                && regProspect.controlAdresse(jTbx_Adresse.getText())
                && regProspect.controlNumTel( jTbx_NumTel.getText())
                && regProspect.controlChiffrAffaire(jTbx_ChiffreAffaire.getText())
                && regProspect.controlNbEmploye(jTbx_NbEmploye.getText())
                && controlDateContrat() && controlInteret()
                && regProspect.controlCommentaire(jTxa_Commentaires.getText())){ 
                
                //  Si tout est bon
                bValid = true;
                
                //  Si on cree un Prospect
                if(!bModif){
                    //  Affichage du numero d identification du Prospect a creer 
                    //  en appelant la methode de class crea_NumIdProspect()
                    this.jTbx_NumIdentification.setText(String.valueOf(Prospect.crea_NumIdProspect()));
                }              
                //  On recupere la valeur des champs saisies
                numId = Integer.parseInt(jTbx_NumIdentification.getText());
                //  Message pour afficher a l utilisateur le numero d identification cree
                if(!bModif){showMessageDialog(null, "Création du Prospect avec le numéro d'identification : "
                        + numId);}
                raison = jTbx_RaisonSociale.getText(); 
                type = jCbx_TypeSociete.getSelectedItem().toString();
                domaine = jTbx_Domaine.getText();            
                adresse = jTbx_Adresse.getText();            
                tel =  jTbx_NumTel.getText();            
                chiffre = Integer.parseInt(jTbx_ChiffreAffaire.getText());                          
                nbrEmp = Integer.parseInt(jTbx_NbEmploye.getText());            
                commentaire = jTxa_Commentaires.getText();            
                date = jXDtp_DateProspection.getDate();            
                interest = choixInteret();  
                //  On instancie un Prospect avec les valeurs saisies
                try {
                    leProspect = new Prospect(numId, raison, type, domaine, adresse, tel, chiffre, commentaire, nbrEmp, date, interest);
                } catch (Exception ex) {
                    Logger.getLogger(Formulaire_Prospect.class.getName()).log(Level.SEVERE, null, ex);
                }
            }            
        }catch(Exception ex){
            showMessageDialog(null, ex.getMessage());
            bValid = false;
        }        
        return bValid;
    }               
  
    //-------------Selection / desselection des CheckBox------------------------
    
    /**
     * Methode qui decoche la la CheckBox NON quand on coche OUI
     * @param evt 
     */
    private void jCkbx_InteretTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCkbx_InteretTrueActionPerformed
        if(jCkbx_InteretFalse.isSelected()){
            jCkbx_InteretFalse.setSelected(false);
        }
    }//GEN-LAST:event_jCkbx_InteretTrueActionPerformed
       
    /**
     * Methode qui decoche la la CheckBox OUI quand on coche NON
     * @param evt 
     */
    private void jCkbx_InteretFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCkbx_InteretFalseActionPerformed
        if(jCkbx_InteretTrue.isSelected()){
            jCkbx_InteretTrue.setSelected(false);
        }
    }//GEN-LAST:event_jCkbx_InteretFalseActionPerformed

    //--------------------------FIN CheckBox------------------------------------
    
    //**************************************************************************//
    //              FIN controle des saisies utilisateur                        //
    //**************************************************************************//
    
    /**
     * Methode associee au bouton valider qui apres verification de la saisie
     * utilisateur creer ou met a jour un Prospect
     * @param evt 
     */
    private void jBtn_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ValiderActionPerformed
        if(validFormulaire()){
            //  Si formulaire de modification
            if(bModif){                              
                // On appelle la methode d instance de creation
                leProspect.MiseAJour();
            }
            //  Sinon c est une creation
            else {
                //  On appelle la methode d instance de mise a jour
                leProspect.Creation();
            }            
            //  On instancie une nouvelle fenetre d 'accueil qui sera mise a jour
            JFrame_Accueil ecranAccueil = null;
            try {
                ecranAccueil = new JFrame_Accueil(1);
            } catch (Exception ex) {
                Logger.getLogger(Formulaire_Client.class.getName()).log(Level.SEVERE, null, ex);
            }
            ecranAccueil.setVisible(true);
            this.dispose();    
        }        
        else{
            showMessageDialog(null, "Erreur lors de la validation du formulaire !");
        }
    }//GEN-LAST:event_jBtn_ValiderActionPerformed

    /**
     * Methode associee au bouton de retour
     * @param evt 
     */
    private void jBtn_RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RetourActionPerformed
        JFrame_Accueil ecranAccueil = null;
        try {
            ecranAccueil = new JFrame_Accueil(1);
        } catch (Exception ex) {
            Logger.getLogger(Formulaire_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        ecranAccueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtn_RetourActionPerformed
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Retour;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JComboBox<String> jCbx_TypeSociete;
    private javax.swing.JCheckBox jCkbx_InteretFalse;
    private javax.swing.JCheckBox jCkbx_InteretTrue;
    private javax.swing.JLabel jLbl_Adresse;
    private javax.swing.JLabel jLbl_ChiffreAffaire;
    private javax.swing.JLabel jLbl_Commentaires;
    private javax.swing.JLabel jLbl_DateContrat;
    private javax.swing.JLabel jLbl_Domaine;
    private javax.swing.JLabel jLbl_Formulaire_Titre;
    private javax.swing.JLabel jLbl_NbEmploye;
    private javax.swing.JLabel jLbl_RaisonSociale;
    private javax.swing.JLabel jLbl_Telephone;
    private javax.swing.JLabel jLbl_TypeSociete;
    private javax.swing.JLabel jLbl_adrMail;
    private javax.swing.JLabel jLbl_numIdentification;
    private javax.swing.JScrollPane jSPane_Commentaires;
    private javax.swing.JTextField jTbx_Adresse;
    private javax.swing.JTextField jTbx_ChiffreAffaire;
    private javax.swing.JTextField jTbx_Domaine;
    private javax.swing.JTextField jTbx_NbEmploye;
    private javax.swing.JTextField jTbx_NumIdentification;
    private javax.swing.JTextField jTbx_NumTel;
    private javax.swing.JTextField jTbx_RaisonSociale;
    private javax.swing.JTextArea jTxa_Commentaires;
    private org.jdesktop.swingx.JXDatePicker jXDtp_DateProspection;
    // End of variables declaration//GEN-END:variables
}
